version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wakaf_app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - ENVIRONMENT=development
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped