version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name tidak diperlukan, Coolify akan menanganinya
    # ports juga tidak diperlukan, Coolify akan menangani exposure ke internet
    volumes:
      - ./:/var/www/html
      # Kita nonaktifkan config kustom untuk sementara agar pasti berhasil
      # - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - ENVIRONMENT=development
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped