version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wakaf_app
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wakaf_db
    restart: always
    environment:
      MYSQL_DATABASE: wakaf
      MYSQL_USER: wakafuser
      MYSQL_PASSWORD: wakafpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
